apiVersion: v1
kind: Service
metadata:
  name: websphere-liberty-controller
spec:
  clusterIP: None
  selector:
    app: websphere-liberty-controller
  ports:
  - port: 9080
    name: http
  - port: 9443
    name: https
  - port: 22
    name: ssh
