apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: websphere-liberty-controller
    app.kubernetes.io/component: websphere-liberty-controller
    app.kubernetes.io/instance: websphere-liberty-controller
  name: websphere-liberty-controller
  namespace: pesourob-liberty
spec:
  serviceName: "websphere-liberty-controller"
  replicas: 1
  selector:
    matchLabels:
      app: websphere-liberty-controller
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: websphere-liberty-controller
    spec:
      containers:
        - image: quay.io/pesourob/pesourob/websphere-liberty-training:latest
          imagePullPolicy: Always
          name: websphere-liberty-controller
          ports:
            - containerPort: 9080
              protocol: TCP
            - containerPort: 9443
              protocol: TCP
            - containerPort: 22
              protocol: TCP
          volumeMounts:
            - name: websphere-liberty-storage
              mountPath: /mnt # Symbolický odkaz na /opt/ibm/wlp/usr/servers/controller - link do not work you should mount pvc under /mnt and copy all from /opt/*  to /mnt and after this action you will be able mount all data on /opt as new pvc under /opt
  volumeClaimTemplates:
  - metadata:
      name: websphere-liberty-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi  # PVC velikost 

