apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"websphere-liberty-controller:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"websphere-liberty-controller\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2024-11-27T10:22:51Z"
  labels:
    app: websphere-liberty-controller
    app.kubernetes.io/component: websphere-liberty-controller
    app.kubernetes.io/instance: websphere-liberty-controller
  name: websphere-liberty-controller
  namespace: pesourob-was-liberty
spec:
  serviceName: "websphere-liberty-controller"
  replicas: 1
  selector:
    matchLabels:
      app: websphere-liberty-controller
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: websphere-liberty-controller
    spec:
      containers:
      - image: quay.io/pesourob/pesourob/websphere-liberty-training@sha256:46295d662105f08def20e916c5d97d396766851dd37dede19867ea62731702a8
        imagePullPolicy: IfNotPresent
        name: websphere-liberty-controller
        ports:
        - containerPort: 9080
          protocol: TCP
        - containerPort: 9443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
  volumeClaimTemplates:
  - metadata:
      name: example-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
